### ISSUE TITLE
DRAFT: Todo before release

### ISSUE THREAD

**Issue by ZyanKLee** [takkt-ag/checkmate#18]
### Documentation
1. [x] Include guidance on how to create the declaration files.
3. [x] Add section about contributions. (cargo +nightly fmt & clippy)
4. [x] Overall CLI help is on the short side.
5. [x] Contribution, License, Affiliation
       https://github.com/takkt-ag/checkmate/pull/24

### General
1. [x] Change copyright to TAKKT I&P in all files + license comment checker adaptations.
       https://github.com/takkt-ag/checkmate/pull/23
2. [x] Example/default file for `checkmate.yaml` config file.
       https://github.com/takkt-ag/checkmate/pull/31
3. [x] Check `TODO:`'s in `rulesets.rs` if any of those have to be addressed before release.
4. [x] Update dependencies (do we want renovate?)
       https://github.com/takkt-ag/checkmate/issues/25
6. [x] Configure clap to wrap at term-width, with a maximum width of 100 characters
